name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docker:
    strategy:
      matrix:
        color: [blue, green]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: axelpavageau/nginx-${{ matrix.color }}:test
          build-args: |
            COLOR=${{ matrix.color }}

      - name: Test
        run: |
          docker run -d --name test-container axelpavageau/nginx-${{ matrix.color }}:test
          docker ps -a
          docker exec test-container curl localhost
          docker stop test-container
          docker rm test-container

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: axelpavageau/nginx-${{ matrix.color }}:latest
          build-args: |
            COLOR=${{ matrix.color }}
